name: Playgroud-V5

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Download_REPO_SUCCESS:
        description: 'Download_REPO_SUCCESS'
        required: false
        default: 'true'

jobs:
  Download_REPO:
    runs-on: ubuntu-18.04
    steps:
      - name: S1
        run: |
          result=${{github.event.inputs.Download_REPO_SUCCESS == 'true'}}
          echo $result
          if [ "$result" = "true" ]; then
            echo "Should continue build"
          else
            exit 2
          fi

  First_Run_Part_1:
    needs: [Download_REPO]
    if: ${{ failure() }}
    runs-on: ubuntu-18.04
    steps:
      - name: Build_SDK
        run: |
          echo 'Build_SDK'

  First_Run_Part_2:
    runs-on: ubuntu-18.04
    needs: [First_Run_Part_1]
    if: ${{ success() }}
    steps:
      - name: First_Run_Part_2
        run: |
          echo "First_Run_Part_2"
  
  Flick_Download_Result:
    runs-on: ubuntu-18.04
    needs: [Download_REPO]
    if: ${{ failure() }}
    steps:
      - name: Should Continue
        run: |
          result=${{ needs.Build_SDK.result == 'success' || needs.Download_Success.result == 'success' }}
          echo "$result"
          if [ "$result" = "true" ]; then
            echo "Should continue build"
          else
            exit 2
          fi

  Pass_Through_Download_Result:
    runs-on: ubuntu-18.04
    needs: [Download_REPO]
    if: ${{ success() }}
    steps:
      - name: Final Log
        run: |
          echo "Pass_Through_Download_Result"

  Iteration_Run:
    runs-on: ubuntu-18.04
    needs: [Pass_Through_Download_Result, First_Run_Part_2]
    if: ${{ needs.Pass_Through_Download_Result.result == 'success' || needs.First_Run_Part_2.result == 'success' }}
    steps:
      - name: Iteration_Run
        run: |
          echo "Iteration_Run"