name: Playgroud-V5

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Download_REPO_SUCCESS:
        description: 'Download_REPO_SUCCESS'
        required: false
        default: 'true'

jobs:
  Download_REPO:
    runs-on: ubuntu-18.04
    steps:
      - name: S1
        run: |
          result=${{github.event.inputs.Download_REPO_SUCCESS == 'true'}}
          echo $result
          if [ "$result" = "true" ]; then
            echo "Should continue build"
          else
            exit 2
          fi

  First_Run_Part_1:
    needs: [Download_REPO]
    if: ${{ needs.Download_REPO.result == 'failure' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Build_SDK
        run: |
          echo 'Build_SDK'

  First_Run_Part_2:
    runs-on: ubuntu-18.04
    needs: [First_Run_Part_1]
    if: ${{ needs.First_Run_Part_1.result == 'success' }}
    steps:
      - name: First_Run_Part_2
        run: |
          echo "First_Run_Part_2"

  Pass_Through_Download_Result:
    runs-on: ubuntu-18.04
    needs: [Download_REPO]
    if: ${{ needs.Download_REPO.result == 'success' }}
    steps:
      - name: Final Log
        run: |
          echo "Pass_Through_Download_Result"

  Iteration_Run:
    runs-on: ubuntu-18.04
    needs: [Pass_Through_Download_Result, First_Run_Part_2]
    if: ${{ needs.Pass_Through_Download_Result.result == 'success' || needs.First_Run_Part_2.result == 'success' }}
    steps:
      - name: Iteration_Run
        run: |
          echo "Iteration_Run"

  Observer_1:
    runs-on: ubuntu-18.04
    needs: [Download_REPO]
    if: ${{ always() }}
    steps:
      - name: Log
        run: |
          echo ${{ needs.Download_REPO.result }}

  Observer_2:
    runs-on: ubuntu-18.04
    needs: [First_Run_Part_1]
    if: ${{ always() }}
    steps:
      - name: Log
        run: |
          echo ${{ needs.First_Run_Part_1.result }}

  Observer_3:
    runs-on: ubuntu-18.04
    needs: [First_Run_Part_2]
    if: ${{ always() }}
    steps:
      - name: Log
        run: |
          echo ${{ needs.First_Run_Part_2.result }}
          
  Observer_4:
    runs-on: ubuntu-18.04
    needs: [Pass_Through_Download_Result]
    if: ${{ always() }}
    steps:
      - name: Log
        run: |
          echo ${{ needs.Pass_Through_Download_Result.result }}

  Observer_5:
    runs-on: ubuntu-18.04
    needs: [Iteration_Run]
    if: ${{ always() }}
    steps:
      - name: Log
        run: |
          echo ${{ needs.Iteration_Run.result }}


