name: Shell

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  Job_A:
    runs-on: ubuntu-18.04
    steps:
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
   

